language: node_js

env:
  - CODECLIMATE_REPO_TOKEN=27355443bbc9aa3c50cffddc9f6fedf22948472b021e30c115e8749095b51ea0

node_js:
  - "12"

matrix:
  include:
    - name: "backend"
      addons:
        apt:
          packages:
            - graphicsmagick
      before_script:
        - node --version
        - npm --version
        - gm version
        - cd api
        - npm ci
        - npm run lint
      script:
        - npm test
      after_success:
        - npm run ci-cover:coveralls
        - npm run ci-cover:prep-codeclimate
        - npm run ci-cover:codeclimate

    - name: "frontend"
      before_script:
        - cd ui
        - npm ci
        - npm run lint
      script:
        - npm test

    - name: "app"
        before_script:
          - cd app
          - npm ci
          - npm run lint:ci
        script:
          - npm test:ci
