version: '3'
services:
  api:
    build: api
    ports:
      - "8000:8000"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./public:/app/public:ro # Unit tests need no readonly mode so remove `:ro`
  ui:
    build: ui
    ports:
      - "3000:3000"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./.env:/app/.env:ro
      - ./public:/app/public:ro
