name: CI
on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: "next/.nvmrc"

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          working-directory: next

      - name: Lint
        run: npm run lint:ci
        working-directory: next

  typecheck:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: "next/.nvmrc"

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          working-directory: next

      - name: 🔎 Type check
        run: npm run typecheck --if-present
        working-directory: next

  unittest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: "next/.nvmrc"

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          working-directory: next

      - name: Unit Test runner
        run: npm run test:ci
        working-directory: next
  e2etest:
    name: Playwright
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout repo
      uses: actions/checkout@v3

    - name: ⎔ Setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: "next/.nvmrc"

    - name: 📥 Download deps
      uses: bahmutov/npm-install@v1
      with:
        working-directory: next

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: next

    - name: Run Playwright tests
      run: npx playwright test
      working-directory: next

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
