name: CI
on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: "next/.nvmrc"

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          working-directory: next

      - name: 🔬 Lint
        run: npm run lint
        working-directory: next

  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: "next/.nvmrc"

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          working-directory: next

      - name: 🔎 Type check
        run: npm run typecheck --if-present
        working-directory: next
